use pizza_analysis;
select * from order_details;
select * from orders;
select * from pizza_types;
select* from pizzas;

-- basic questions
-- FInd the total number of orders placed
select  count(distinct order_id) as total_orders from order_details;

-- Calculate the total revenue generated by from pizza sales
select order_details.pizza_id,order_details.quantity,pizzas.price
from order_details
join pizzas on pizzas.pizza_id = order_details.pizza_id;
-- to get the answer
select sum(order_details.quantity*pizzas.price) as total_revenue
from order_details
join pizzas on pizzas.pizza_id = order_details.pizza_id;

-- Identify the highest priced pizza using LIMIT functions
select pizza_types.name as pizza_name,pizzas.price as pizza_price
from pizza_types
join pizzas on pizzas.pizza_type_id = pizza_types.pizza_type_id
order by pizza_price desc limit 1;
-- same but using [window functions and CTE] not by [LIMIT and JOIN]
with cte as(
select pizza_types.name as pizza_name,pizzas.price as pizza_price,
rank() over(order by price desc) as rnk
from pizza_types join pizzas on pizzas.pizza_type_id = pizza_types.pizza_type_id)
select* from cte where rnk = 1;

-- identify the most common pizza size ordered
select pizzas.size,count(distinct order_id) as no_of_orders, sum(quantity) as total_quantity
from order_details
join pizzas on pizzas.pizza_id = order_details.pizza_id
group by size
order by total_quantity desc;

-- list the top 5 ordered pizza_types along with their quantities
select pizzas.pizza_type_id as PizzaType,sum(order_details.quantity) as TotalQuantities
from pizzas
join order_details on pizzas.pizza_id = order_details.pizza_id
group by PizzaType
order by TotalQuantities desc limit 5;

-- join the necessary tables to find the total quantity of each pizza category ordered
select pizza_types.category as PizzaCategory,sum(order_details.quantity) as TotalQuantity
from order_details
join pizzas on order_details.pizza_id = pizzas.pizza_id
join pizza_types on pizzas.pizza_type_id = pizza_types.pizza_type_id
group by PizzaCategory
order by TotalQuantity desc;

-- determine the distribution of orders by hour of the day
select hour(time) as OrderHour ,count(distinct order_id) as TotalOrders
from orders
group by Orderhour
order by TotalOrders desc;

-- Find the Category wise distribution of pizzas
select category,count(distinct pizza_type_id) as NoOfPizzas
from pizza_types
group by category
order by NoOfPizzas;

-- calculate the average number of pizzas ordered per day(Direct calculation and CTE) 
select sum(order_details.quantity) / count(DISTINCT orders.date) AS AveragePizzasPerDay
from orders
join order_details 
on orders.order_id = order_details.order_id;
-- using CTE
with cte as(
select orders.date as datee,sum(order_details.quantity) as totalpizzathatday
from orders 
join order_details
on orders.order_id = order_details.order_id
group by datee)
select avg(totalpizzathatday) as AvgPizzasPerday
from cte;
-- using subquery
select avg(totalpizzathatday) as AvgPizzasPerday from(
select orders.date as datee,sum(order_details.quantity) as totalpizzathatday
from orders 
join order_details
on orders.order_id = order_details.order_id
group by datee) as A;

-- determine the top 3 most ordered pizza types based on revenue
select pizza_types.name  as PizzaTypeName ,sum(order_details.quantity*pizzas.price) as RevenueFromPizza
from order_details
join pizzas on order_details.pizza_id = pizzas.pizza_id
join pizza_types on pizza_types.pizza_type_id = pizzas.pizza_type_id
group by PizzaTypeName
order by RevenueFromPizza desc limit 3;
-- using window functions
select PizzaTypeName,RevenueFromPizza,rnk from(
select pizza_types.name  as PizzaTypeName ,sum(order_details.quantity*pizzas.price) as RevenueFromPizza,
row_number() over( order by sum(order_details.quantity*pizzas.price) desc) as rnk
from order_details
join pizzas on order_details.pizza_id = pizzas.pizza_id
join pizza_types on pizza_types.pizza_type_id = pizzas.pizza_type_id
group by pizzaTypeName )as A
where rnk<=3;


-- Advanced
-- calculate the percentage contribution of each pizza type to total revenue
with CTE as(
-- Step 1: Get total revenue for each pizza type
select pizza_types.name as PizzaTypeName ,sum(order_details.quantity*pizzas.price) as Revenue
from order_details
join pizzas on order_details.pizza_id= pizzas.pizza_id
join pizza_types on pizzas.pizza_type_id = pizza_types.pizza_type_id
group by PizzaTypeName)
-- Step 2: Divide each revenue by the Grand Total
select PizzaTypeName,Revenue,round((Revenue/sum(Revenue) over())*100,2) as PercentageContribution
from CTE 
order by PercentageContribution desc;


-- analyze the cumulative revenue generated over time
-- use of aggregate window function(to get the cumulative sum)
with CTE as(
select orders.date as datee ,sum(quantity*price) as Revenue
from order_details
join orders on order_details.order_id = orders.order_id
join pizzas on order_details.pizza_id = pizzas.pizza_id
group by datee
)
select datee,Revenue,sum(Revenue) over(order by datee) as CumulativeSum
from CTE 
order by datee;


-- determine the top 3 most ordered pizza types based on revenue for each pizza category
with CTE as(
select category,name,sum(quantity*price) as revenue
from order_details
join pizzas on pizzas.pizza_id = order_details.pizza_id
join pizza_types on pizza_types.pizza_type_id = pizzas.pizza_type_id
group by category,name),
cte1 as (
select category,name,revenue,rank() over(partition by category order by revenue desc) as rnk
from cte)
select category ,name,revenue
from cte1
where rnk in (1,2,3)
order by category,name,revenue desc;






